export {default as logo} from "./logo.png"
export {default as illustration} from "./codingcuate.png"
export {default as profilepic} from "./BEEBE BERRY.png"
export {default as GitHubPic} from "./GitHub-Repo-Site.png"
// export {default as logo} from "./logo.png"